"""empty message

Revision ID: 2a3ce19a7a5b
Revises: d4c79e829afa
Create Date: 2021-11-04 16:18:08.791794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3ce19a7a5b'
down_revision = 'd4c79e829afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('is_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolists', 'is_completed')
    # ### end Alembic commands ###
